@c
@c README.texi -- Description, distribution, obtaining, contact,
@c                bug reports, contribution, donation and hacking;
@c
@c Copyright (C) 2010, 2013 Bruno Félix Rezende Ribeiro
@c <oitofelix@gnu.org>
@c
@c Permission is granted to copy, distribute and/or modify this
@c document under the terms of the GNU Free Documentation License,
@c Version 1.3 or any later version published by the Free Software
@c Foundation; with no Invariant Sections.
@c
@c You should have received a copy of the GNU Free Documentation
@c License along with this program.  If not, see
@c <http://www.gnu.org/licenses/>.
@c

@c %**start of header
@ifclear manual
@setfilename README
@documentencoding UTF-8
@c @documentlanguage en_US
@firstparagraphindent insert
@footnotestyle end
@settitle README
@end ifclear
@include package.texi
@c %**end of header





@c --- Macros;

@c --- --- metaSection
@macro metaSection{name}
@ifset file
@node \name\
@chapter \name\
@end ifset
@ifset manual
@node \name\
@section \name\
@end ifset
@ifset homepage
@anchor{\name\}
@majorheading \name\
@end ifset
@end macro





@c --- manual: Menu;
@ifset manual
This chapter briefly explains for what this package is intended, what
are the rules for its distribution, how to get a copy of it, how to
contact its community, how to fill bug reports, how to contribute to
the package, how to make donations to support its development and how
to get started hacking the code.  If you have checked out the source
tree from the CVS repository see @ref{Hacking}.

@menu
* Description::    What this package is all about;
* Distribution::   The user's right to modify and redistribute;
* Getting a copy:: GNU FTP server and CVS;
* Contact::        Mailing list and IRC;
* Bug reporting::  Support and bug trackers;
* Contributing::   Several ways to help program's development;
* Donating::       Supporting developer's work;
* Hacking::        Get started with CVS checkout;
@end menu
@end ifset





@c --- homepage: Navigation bar;
@ifset homepage
@include navigation.texi

@majorheading Main

@multitable @columnfractions .1 .1 .1 .1 .1 .1
@headitem @ref{Download}
@tab @ref{Contact}
@tab @ref{Bug reporting}
@tab @ref{Contributing}
@tab @ref{Donating}
@tab @ref{Hacking}
@end multitable
@end ifset





@c --- file: Copying notice;
@ifset file
@set FILE README
@include copying.texi
@insertcopying
@end ifset





@c --- file: Table of contents;
@ifset file
@sp 1
@noindent
--- Table of Contents ---
@contents
@sp 2
@end ifset





@c --- file: Preface;
@ifset file
@unnumbered Preface

This file briefly explains for what this package in intended, what are
the rules for its distribution, how to get a copy of it, how to
contact the community, how to fill bug reports, how to contribute to
the package, how to make donations to support its development and how
to get started hacking the code.  If you have checked out the source
tree from the CVS repository see @ref{Hacking}.  For other information
about this package you can check the following files found in the top
level directory of the distribution:

@table @file
@item NEWS
User-visible changes since previous versions;
@item TODO
Features we want to see implemented someday;
@item AUTHORS
List of major contributors;
@item THANKS
List of minor contributors;
@c @item BUGS
@c Bugs you must be aware of;
@item DONORS
People who supported the development by donations;
@item INSTALL
Generic build and installation instructions;
@item ABOUT-NLS
Internationalization and localization matters;
@item COPYING
The program license;
@item COPYING.DOC
The documentation license;
@item ChangeLog
Detailed list of changes of the source code;
@end table

Information about the GNU operating system, the GNU Project and the
Free Software Movement are included in the distribution --- for your
pleasure --- in the form of some articles by Richard Stallman (RMS).
See the top-level files:

@table @file
@item THE-GNU-MANIFESTO
The GNU Manifesto;
@item THE-GNU-PROJECT
The GNU Project history;
@item LINUX-AND-THE-GNU-SYSTEM
Linux and the GNU system;
@item WHY-SOFTWARE-SHOULD-NOT-HAVE-OWNERS
Why Software Should Not Have Owners;
@end table

For more information about this program you can visit its home page at
@url{@value{webPage}}.  If you want to receive notifications about new
releases of this program or important issues related to it, subscribe
to the mailing list, as described in @ref{Contact}, or subscribe to
the package atom feed @url{@value{atomFeed}}.
@end ifset





@c --- Description;
@ifset file
@chapter Description
@end ifset
@ifset manual
@node Description
@section Description
@end ifset

@ifclear manual
@cartouche
@quotation Manifesto
On the internet there is a gigantic quantity of optical disc image
files in numerous formats.  Countless times we need to burn some of
them.  Some time ago I needed it, but I came across a file format
extremely irritating for a Free Software user like me: a CD layout
descriptor file, with @file{.ccd} suffix, generated by a proprietary
software called CloneCD.  I searched the internet for a way to burn
that file on the GNU+Linux-Libre system, but I only found a lot of
people asking for a solution on a lot of forums, and getting the
unanimous answer: no way!  At first I could not believe at that point
there was no option.  Then, with a little bit of patience and
research, I wrote some code to convert that files to a format much
more common and accessible, an ad-hoc standard in the GNU operating
system: the CUE sheet format.  So I could burn a lot of what I wanted!
I wondered whether it would be useful for others@dots{} and here is
the result!
@author Bruno Félix Rezende Ribeiro (oitofelix)
@end quotation
@end cartouche
@end ifclear

GNU ccd2cue is a CCD sheet to CUE sheet converter.  It supports the
full extent of CUE sheet format expressiveness, including mixed-mode
discs and CD-Text meta-data.  It plays an important role for those who
need to use optical disc data which is only available in the
proprietary sheet format CCD, but don't want to surrender their
freedom.  It fills an important gap in the free software world because
before its conception it was impossible to use complex forms of
optical disc data laid out by CCD sheets in a whole/holy free
operating system.

@ifset homepage
@multitable {} {}
@item @image{images/gpl} @tab
@emph{The GNU ccd2cue software is free software}; you can redistribute
it and/or modify it under the terms of the GNU
@acronym{@url{@value{progLicenseURL}, GPL}, General Public Licence} as
published by the @acronym{FSF, Free Software Foundation}; either
version 3, or (at your option) any later version.
@end multitable
@end ifset

The GNU ccd2cue documentation is also intended to be a reference
documentation for both sheet format specifications.  That way we can
reverse engineer the secret CCD sheet proprietary format only once and
then make the information available for developers in order to benefit
all free software users that want their software to be interoperable.
The CUE sheet format is not a secret, but with this package we take
the opportunity to ensure that its specification is available under a
free documentation license for the sake of the whole free software
community.

@ifset homepage
@multitable {} {}
@item @image{images/fdl} @tab
@emph{The GNU ccd2cue documentation is free documentation}; you can
redistribute it and/or modify it under the terms of the GNU
@acronym{@url{@value{docLicenseURL}, FDL}, Free Documentation Licence}
as published by the FSF --- with no Invariant Sections; either version
1.3, or (at your option) any later version.
@end multitable
@end ifset





@c --- file, manual: Distribution;
@ifclear homepage
@metaSection Distribution

This program is @dfn{free software}; this means that everyone is free
to use it and free to redistribute it under certain conditions.  This
program is not in the public domain; it is copyrighted and there are
restrictions on its distribution, but these restrictions are designed
to permit everything that a good cooperating citizen would want to do.
What is not allowed is to try to prevent others from further sharing
any version of this program that they might get from you.  The precise
conditions are found in the @inlineifset{file, GNU General Public
License (@file{COPYING} file)}@inlineifset{manual, GNU
@acronym{@url{@value{progLicenseURL}, GPL}, General Public Licence}}.
The program manual is covered by the @inlineifset{file, GNU Free
Documentation License (@file{COPYING.DOC} file)}@inlineifset{manual,
GFDL (@ref{GNU Free Documentation License})}.  This license is similar
in spirit to the GNU General Public License, but is more suitable for
documentation.
@end ifclear





@c --- file, manual: Getting a copy;
@ifclear homepage
@metaSection Getting a copy

One way to get a copy of this program is from someone else who has it.
You need not ask for our permission to do so, or tell any one else;
just copy it.  You may also receive this program when you buy a
computer.  Computer manufacturers are free to distribute copies on the
same terms that apply to everyone else.  These terms require them to
give you the full sources, including whatever changes they may have
made, and to permit you to redistribute the program received from them
under the usual terms of the GNU General Public License.  In other
words, the program must be free for you when you get it, not just free
for the manufacturer.

If you have access to the Internet, you can get the latest
distribution version of this program at @url{@value{ftpDir}}.  Please,
use a mirror if possible; you will be automatically redirected to the
nearest mirror at @url{@value{ftpMirrorDir}}.

A CVS repository, where the development takes place, is also
available.  It maintains the full history of modifications of every
single source file.  You can checkout any given revision of any file
or get a snapshot of the entire source tree in a particular desired
state.  Special build tools, as described in @ref{Hacking}, are
required to build from those checkouts, though.  Notably, to stay up
to date with the latest developments in the source tree, you can
anonymously checkout the repository with the following command:
@example
cvs -z9 -d:pserver:anonymous@@@value{CVSurl} co @value{GNUid}
@end example
@end ifclear





@c --- homepage: Download;
@ifset homepage
@anchor{Download}
@majorheading Download

@strong{The current stable release is @value{VERSION}} (released
@value{DATE}).  You can download it here:
@url{@value{ftpMirrorTarball}, @value{tarball}},
@url{@value{ftpMirrorTarSign}, @value{tarSign}} (alternative:
@url{@value{ftpTarball}, @value{tarball}}, @url{@value{ftpTarSign},
@value{tarSign}}).

You can find that and earlier releases at a nearby
@url{@value{ftpMirrorDir}, GNU@tie{}ftp@tie{}mirror}; or if automatic
redirection does not work use the @url{@value{ftpDir},
GNU@tie{}main@tie{}ftp@tie{}server}.

This release is signed by @emph{@value{signer}}.  His key ID is
@code{@value{keyID}}.  You can retrieve that key from a key server
using the command
@example
gpg --recv-keys @value{keyID} --keyserver hkp://keys.gnupg.net
@end example

Check the key's authenticity with the command
@example
gpg --fingerprint @value{keyID} | sed -n '/^[[:blank:]]\+Key/s/^.*= //p'
@end example

It must print the following fingerprint:
@example
@value{fingerprint}
@end example

Otherwise something is wrong!  In that case don't use the downloaded
tarball and contact the developers as described in @ref{Contact}.

A CVS repository, where the development takes place, is also
available.  To stay up to date with the latest developments in the
source tree, you can anonymously checkout the repository with the
following command:
@example
cvs -z9 -d:pserver:anonymous@@@value{CVSurl} co @value{GNUid}
@end example
@end ifset





@c --- Contact
@metaSection Contact

You can get in touch with other users and the developers of this
program subscribing to the mailing list.  Anyone is welcome to join
the list; to do so, visit the @url{@value{mailBugWeb},
@value{mailBugName} web interface}.  You can use this list for all
discussion, including asking for help and bug reporting, although the
preferred method for reporting bugs is the dedicated bug tracking web
interface described in @ref{Bug reporting}.  To post a message to all
the list members, send email to @email{@value{mailBugAddr}}.  To see
the collection of prior postings to the list, visit the
@url{@value{mailBugArch}, @value{mailBugName} archive}.

If you feel somewhat chatty, eager for a somewhat more instantaneous
response from community, you can join us on our friendly IRC channel:
@samp{@value{IRCurl}}.





@c --- Bug reporting
@metaSection Bug reporting

If you come across some problem and need help you can contact the
community as described in @ref{Contact}.  If you think you found a
bug, but is not quite sure about it, you can instead ask for support
on our @url{@value{supportTrack}, support tracker}.  We will revise
your post, advise you and take the appropriate measures.  If you are
confident you have found a bug, you can submit a bug report directly
at our @url{@value{bugTrack}, bug tracker}.  Please, when reporting a
bug include enough information for the maintainers to reproduce the
problem.  Generally speaking, that means:

@itemize
@item
The contents of any input files necessary to reproduce the bug and
command line invocations of the program(s) involved (crucial!).
@item
A description of the problem and any samples of the erroneous output.
@item
The version number of the program(s) involved (use
@option{--version}).
@item
Hardware, operating system, and compiler versions (@code{uname -a}).
@item
Unusual options you gave to configure, if any (see
@file{config.status}).
@item
Anything else that you think would be helpful.
@end itemize





@c --- Contributing
@metaSection Contributing

This program is a collaborative effort and we encourage contributions
from anyone and everyone --- your help is very much appreciated.  You
can help in many ways:

@itemize
@item
Donate to developers in order to support their work.  See
@ref{Donating}.
@item
Write documentation.  We are specially in need to complete the CCD
sheet format specification.
@item
Help users in the mailing list and IRC channel.
@item
Find and report bugs.  @xref{Bug reporting}.
@item
Fix reported bugs.
@item
Implement new feature ideas.
@item
Write test cases.
@item
Check the documentation against the implementation.
@item
Translate the program strings to other languages.
@end itemize

You can join the development team to contribute code and documentation
at the @url{@value{develPage}, development page}.  Patches are most
welcome, but contributed code should follow the @ref{,,, standards,
GNU Coding Standards}.  If it doesn't, we'll need to find someone to
fix the code before we can use it.  It is also necessary that the
contributor be willing to assign their copyright to the FSF, since the
developers plan to make it officially part of the GNU operating system
and they want FSF to enforce the program's license.  To get started
hacking see @inlinefmtifelse{html, @url{README.html#Hacking, how to
hack}, @ref{Hacking}}.





@c --- Donating;
@metaSection Donating

If you find this program useful, please @strong{send a donation} to
its developers to support their work.  If you use this program at your
workplace, please suggest that the company make a donation.  We
appreciate contributions of any size -- donations enable us to spend
more time working on this package, and help cover our infrastructure
expenses.

If you'd like to make a donation of any value, please send it to the
following Bitcoin address:

@example
@value{btcAddr}
@end example

Since we aren't a tax-exempt organization, we can't offer you a tax
deduction, but for all donations over 0.05@tie{}BTC, we'd be happy to
recognize your contribution on the @url{DONORS.html, donors@tie{}page}
and on @file{DONORS} file for the next release.

We are also happy to consider making particular improvements or
changes, or giving specific technical assistance, in return for a
substantial donation over 0.5@tie{}BTC.  If you would like to discuss
this possibility, write to us at @email{@value{mailPrivAddr}}.

Another possibility is to pay a software maintenance fee.  Again,
write to us about this at @email{@value{mailPrivAddr}} to discuss how
much you want to pay and how much maintenance we can offer in return.

@center @strong{Thanks for your support!}
@sp 1





@c --- Hacking;
@metaSection Hacking

@noindent
The development sources are available through CVS at Savannah:

@display
@value{CVSsavannah}
@end display

If you are getting the sources from CVS (or change
@file{configure.ac}), you'll need to have Automake, Autoconf and
Gettext installed to (re)build.  You'll also need help2man.  All of
these programs are available from @url{@value{ftp}}.

After getting the CVS sources, and installing the tools above, you can
run @code{./bootstrap} to do a fresh build.  After that first time,
running @command{make} should suffice.  See file @file{INSTALL}.

When modifying the sources, or making a distribution, more is needed,
as follows:

@itemize
@item
This distribution also uses @url{https://www.gnu.org/software/gnulib,
Gnulib} to share common files, stored as a submodule in git.
@item
When updating gettext, besides the normal installation on the system,
it is necessary to run @code{gettextize -f} in this hierarchy to
update the @file{po/} infrastructure.  After doing so, rerun
@code{gnulib-tool --import} since otherwise older files will have been
imported.  @xref{,,, gnulib, Gnulib Manual}, for more information.
@end itemize





@c --- homepage: Footer;
@ifset homepage
@include footer.texi
@end ifset
